version: '3.4'
services:
  langchain:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8000:8000
    restart: always
    environment:
      OPENAI_API_KEY: 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
      GOOGLE_CLOUD_PROJECT_ID: tsmccareerhack2024-tsid-grp3
      GOOGLE_CLOUD_STORAGE_BUCKET: tsmccareerhack2024-tsid-grp3-bucket
      HUGGINGFACEHUB_API_TOKEN: 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
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8765'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.23.4
    ports:
      - 8765:8765
      - 50051:50051
    volumes:
      - /var/weaviate:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'