name: CI/CD Workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: objectdetection-363706
      GAR_REPOSITORY: scon

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest

    - name: Build Docker image
      run: docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/lc-app:${{ github.sha }} .

    - name: Log in to Google Artifacts Registry
      run: echo ${{ secrets.GAR_JSON_KEY }} | docker login -u _json_key --password-stdin https://asia-east1-docker.pkg.dev

    - name: Push Docker image to GCR
      run: docker push gcr.io/${{ env.GCP_PROJECT_ID }}/lc-app:${{ github.sha }}

